const DEXROUTER_ABI = [
    "function smartSwapByOrderId(uint256 orderId, tuple(uint256 fromToken, address toToken, uint256 fromTokenAmount, uint256 minReturnAmount, uint256 deadLine) baseRequest, uint256[] batchesAmount, tuple(address[] mixAdapters, address[] assetTo, uint256[] rawData, bytes[] extraData, uint256 fromToken)[][] batches, tuple(uint256 fromToken, address toToken, address receiver, address payer, uint256 fromTokenAmount, uint256 minReturnAmount, uint256 deadLine, uint256 orderId, bool isToB, bytes settlerData)[] extraData) external payable returns (uint256 returnAmount)",
    "function unxswapByOrderId(uint256 srcToken, uint256 amount, uint256 minReturn, bytes32[] pools) external payable returns (uint256 returnAmount)",
    "function smartSwapByInvest(tuple(uint256 fromToken, address toToken, uint256 fromTokenAmount, uint256 minReturnAmount, uint256 deadLine) baseRequest, uint256[] batchesAmount, tuple(address[] mixAdapters, address[] assetTo, uint256[] rawData, bytes[] extraData, uint256 fromToken)[][] batches, tuple(uint256 fromToken, address toToken, address receiver, address payer, uint256 fromTokenAmount, uint256 minReturnAmount, uint256 deadLine, uint256 orderId, bool isToB, bytes settlerData)[] extraData, address to) external payable returns (uint256 returnAmount)",
    "function smartSwapByInvestWithRefund(tuple(uint256 fromToken, address toToken, uint256 fromTokenAmount, uint256 minReturnAmount, uint256 deadLine) baseRequest, uint256[] batchesAmount, tuple(address[] mixAdapters, address[] assetTo, uint256[] rawData, bytes[] extraData, uint256 fromToken)[][] batches, tuple(uint256 fromToken, address toToken, address receiver, address payer, uint256 fromTokenAmount, uint256 minReturnAmount, uint256 deadLine, uint256 orderId, bool isToB, bytes settlerData)[] extraData, address to, address refundTo) public payable returns (uint256 returnAmount)",
    "function uniswapV3SwapTo(uint256 receiver, uint256 amount, uint256 minReturn, uint256[] pools) external payable returns (uint256 returnAmount)",
    "function smartSwapTo(uint256 orderId, address receiver, tuple(uint256 fromToken, address toToken, uint256 fromTokenAmount, uint256 minReturnAmount, uint256 deadLine) baseRequest, uint256[] batchesAmount, tuple(address[] mixAdapters, address[] assetTo, uint256[] rawData, bytes[] extraData, uint256 fromToken)[][] batches, tuple(uint256 fromToken, address toToken, address receiver, address payer, uint256 fromTokenAmount, uint256 minReturnAmount, uint256 deadLine, uint256 orderId, bool isToB, bytes settlerData)[] extraData) external payable returns (uint256 returnAmount)",
    "function unxswapTo(uint256 srcToken, uint256 amount, uint256 minReturn, address receiver, bytes32[] pools) public payable returns (uint256 returnAmount)",
    "function uniswapV3SwapToWithBaseRequest(uint256 orderId, address receiver, tuple(uint256 fromToken, address toToken, uint256 fromTokenAmount, uint256 minReturnAmount, uint256 deadLine) baseRequest, uint256[] pools) external payable returns (uint256 returnAmount)",
    "function unxswapToWithBaseRequest(uint256 orderId, address receiver, tuple(uint256 fromToken, address toToken, uint256 fromTokenAmount, uint256 minReturnAmount, uint256 deadLine) baseRequest, bytes32[] pools) external payable returns (uint256 returnAmount)",
    "function swapWrap(uint256 orderId, uint256 rawdata) external payable",
    "function swapWrapToWithBaseRequest(uint256 orderId, address receiver, tuple(uint256 fromToken, address toToken, uint256 fromTokenAmount, uint256 minReturnAmount, uint256 deadLine) baseRequest) external payable",
    "function dagSwapByOrderId(uint256 orderId, tuple(uint256 fromToken, address toToken, uint256 fromTokenAmount, uint256 minReturnAmount, uint256 deadLine) baseRequest, tuple(address[] mixAdapters, address[] assetTo, uint256[] rawData, bytes[] extraData, uint256 fromToken)[] paths) external payable returns (uint256 returnAmount)",
    "function dagSwapTo(uint256 orderId, address receiver, tuple(uint256 fromToken, address toToken, uint256 fromTokenAmount, uint256 minReturnAmount, uint256 deadLine) baseRequest, tuple(address[] mixAdapters, address[] assetTo, uint256[] rawData, bytes[] extraData, uint256 fromToken)[] paths) external payable returns (uint256 returnAmount)",
];

module.exports = {
    DEXROUTER_ABI
};
